#!/usr/bin/env bash
# Bash completion for gander.
# Generated by `gander completion bash`.

_gander_completions() {
    local cur prev cmds
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    if [[ ${COMP_CWORD} -eq 1 ]]; then
        cmds="signup share watch remove list comments mcp skill uninstall status stop logs runner manage auth completion --upgrade upgrade --help -h -help help"
        COMPREPLY=( $(compgen -W "${cmds}" -- "${cur}") )
        return 0
    fi

    case "${COMP_WORDS[1]}" in
        signup)
            COMPREPLY=( $(compgen -W "--email --force" -- "${cur}") )
            return 0
            ;;
        share|watch)
            case "${prev}" in
                --comments)
                    COMPREPLY=( $(compgen -W "anyone team" -- "${cur}") )
                    return 0
                    ;;
                --comment-visibility)
                    COMPREPLY=( $(compgen -W "public team" -- "${cur}") )
                    return 0
                    ;;
            esac
            local share_flags="--watch --foreground --comments --comment-visibility --private --no-comments"
            if [[ "${COMP_WORDS[1]}" == "watch" ]]; then
                share_flags="--foreground --comments --comment-visibility --private --no-comments"
            fi
            COMPREPLY=( $(compgen -W "${share_flags}" -- "${cur}") )
            COMPREPLY+=( $(compgen -f -- "${cur}") )
            return 0
            ;;
        remove)
            COMPREPLY=( $(compgen -W "--all --pick --yes --non-interactive" -- "${cur}") )
            return 0
            ;;
        status)
            COMPREPLY=()
            return 0
            ;;
        stop)
            COMPREPLY=( $(compgen -W "--all --yes --non-interactive" -- "${cur}") )
            COMPREPLY+=( $(compgen -f -- "${cur}") )
            return 0
            ;;
        comments)
            COMPREPLY=( $(compgen -f -- "${cur}") )
            return 0
            ;;
        mcp)
            COMPREPLY=( $(compgen -W "install" -- "${cur}") )
            return 0
            ;;
        skill)
            COMPREPLY=( $(compgen -W "install" -- "${cur}") )
            return 0
            ;;
        uninstall)
            COMPREPLY=( $(compgen -W "--yes --non-interactive --keep-config" -- "${cur}") )
            return 0
            ;;
        logs)
            COMPREPLY=( $(compgen -W "--follow --no-follow" -- "${cur}") )
            return 0
            ;;
        runner)
            COMPREPLY=( $(compgen -W "install uninstall" -- "${cur}") )
            return 0
            ;;
        completion)
            COMPREPLY=( $(compgen -W "bash zsh" -- "${cur}") )
            return 0
            ;;
        auth)
            COMPREPLY=()
            return 0
            ;;
        -upgrade|--upgrade|upgrade)
            COMPREPLY=()
            return 0
            ;;
        *)
            COMPREPLY=()
            return 0
            ;;
    esac
}

complete -F _gander_completions gander
