#!/usr/bin/env bash
# Bash completion for gander.
# Generated by `gander completion bash`.

_gander_completions() {
    local cur prev cmds
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    if [[ ${COMP_CWORD} -eq 1 ]]; then
        cmds="signup share remove list manage completion --upgrade upgrade --help -h -help help"
        COMPREPLY=( $(compgen -W "${cmds}" -- "${cur}") )
        return 0
    fi

    case "${COMP_WORDS[1]}" in
        signup)
            COMPREPLY=( $(compgen -W "--email --force" -- "${cur}") )
            return 0
            ;;
        share)
            COMPREPLY=( $(compgen -W "--watch" -- "${cur}") )
            return 0
            ;;
        remove)
            COMPREPLY=( $(compgen -W "--all --pick --yes --non-interactive" -- "${cur}") )
            return 0
            ;;
        completion)
            COMPREPLY=( $(compgen -W "bash zsh" -- "${cur}") )
            return 0
            ;;
        -upgrade|--upgrade|upgrade)
            COMPREPLY=()
            return 0
            ;;
        *)
            COMPREPLY=()
            return 0
            ;;
    esac
}

complete -F _gander_completions gander
